- next/app/api/sim/furnitures/route.ts
- next/components/sim/SimSideView.tsx
- next/components/sim/side/SideItems.tsx
- next/package-lock.json
- next/package.json
그리고 한 번씩 가구 초기 데이터가 다르게 나오는데, 그거는 DEBUG 모드에서 2번씩 호출되는 버그 때문에 생기는거 같아서, 배포한 후 다시 테스트 해봐야할거 같습니다.
> fix: 시뮬레이터 사이드바 최종본

- next/app/api/rooms/search/route.ts
- next/app/api/sim/search/route.ts
- next/app/search/page.tsx
- next/components/layout/Header.tsx
- next/components/main/SearchBar.tsx
- next/components/search/SearchBar.tsx
- next/components/search/SortedHouseList.tsx
- next/lib/api/furSearch.ts
- next/lib/api/rooms.ts
- next/lib/handler.ts
- 상세 페이지 접근 후 뒤로 가기 버튼 클릭 시 정보 유지 안됨.
- ex) query, type 등
> feat: 검색 기능

- socket/package-lock.json
- socket/package.json
- socket/src/chat/chat.gateway.ts
> feat : 웹소켓 채티방 입퇴장, 메시지 전송 구현중

- next/app/api/rooms/route.ts
- next/app/api/sim/load/[room_id]/route.ts
- next/app/components/FloorPlanEditor.jsx
- next/app/sim/[id]/page.tsx
- next/app/sim/components/ControlPanel.jsx
- next/app/sim/store/useStore.js
- next/lib/prisma.ts
- `/create` 캔버스 크기 동적으로 축소되도록 수정
- `/create` 기능 추가
- 벽 길이 조정 가능
- 이미지 로드시 그리드 위에 표시
- 일부 선만 지울수있는 기능 (문 만들기 등)
- 모든 방향에서 치수(mm)  올바른 방향으로 표시
- 임시 방 id 부여방식 -> 무조건 정식 방 id 부여방식으로 변경
- 시뮬레이터 : 3D 벽 비율 개선
- `app/sim/stor/useStor.js` 의 `wallscaleFactor` 변수를 수정하시면 임의로 조정할 수 있습니다.
- 시뮬레이터 : 벽이 있는 부분만 바닥을 생성하도록 변경
---
그리고 테스트하느라 room.room_walls 에 이상한 값들이 들어간 row가 많은데  나중에 삭제하겠습니다
> feat : 도면 생성 및 모델링 , 시뮬레이터 개선

- next/app/sim/components/ControlPanel.jsx
- next/components/sim/side/SideTitle.tsx
- next/lib/api/saveRoom.ts
> feat: 방 나가기 버튼 생성 & 저장 후 나가기

- next/app/components/FloorPlanEditor.jsx
- next/package-lock.json
- next/package.json
- 모눈종이 배경이 짤리는 문제 수정
- 오늘의집처럼 드래그로 이동 가능
- 버튼 ON/OFF 가능
- 왼쪽 위 홈 아이콘 클릭시 메인 홈페이지로 이동
- 오른쪽 사이드바 토글 기능 구현
> fix : /create 수정

- .github/workflows/wheretoput_CI.yml
- next/app/api/furniture-import/route.js
- next/app/sonnet4_api.js
- socket/test/app.e2e-spec.ts
- socket/tsconfig.json
> fix: CI test 때문에 수정했던 socket 파일 되돌려둠 '|| true' 적용해서 CI 실행

- next/app/sim/[id]/page.tsx
벽 투명화 기능이 잘 작동 안하는 것 같아서
```
const updateTransparency = () => {
if (!meshRef.current) return;
if (!enableWallTransparency) {
setOpacity(1.0);
return;
}
```
`enableWallTransparency` -> `!enableWallTransparency`로 수정했습니다.
> fix: 벽 투명화 on/off 기능

- next/components/chat/ChatButton.tsx
- 첫입장, 재입장, 메시지 전송시 맨아래로 스크롤 가게 수정
> fix : 스크롤 문제해결

- next/app/api/chat/download-image/route.ts
- next/app/api/chat/upload-image/route.ts
- next/app/api/upload-url/getFileUrl/route.ts
- next/components/chat/ChatButton.tsx
- next/components/chat/components/ChatPopup.tsx
- next/components/chat/components/ChatRoomView.tsx
- next/components/chat/components/shared/ImageModal.tsx
- next/components/chat/components/shared/MessageBubble.tsx
- next/components/chat/hooks/useChatMessages.ts
- next/components/chat/types/chat-types.ts
- 이미지 전송 버튼 추가 
- 각 버튼별로 모션 추가
- 이미지 클릭시 모달로 볼수있게 변경
- 저장하기, 끄기 버튼 추가
- 이미지 전송시 미리보기 기능 구현
- 이미지와 채팅 동시에 보낼시 이미지 먼저 보내지도록 구현
- 엔터키로 전송시 메시지만 보내지던것 수정
> feat : 이미지 전송 기능 구현 및 모션추가

- next/app/api/backend/rooms/[id]/leave/route.ts
- next/app/api/backend/rooms/route.ts
- next/components/chat/ChatButton.tsx
- next/components/chat/components/ChatListView.tsx
- next/components/chat/components/ChatPopup.tsx
- next/components/chat/components/ChatRoomView.tsx
- next/components/chat/components/shared/ContextMenu.tsx
- next/components/chat/components/shared/DeleteChatModal.tsx
- next/components/chat/hooks/useChatMessages.ts
- next/components/chat/hooks/useChatRooms.ts
- socket/src/chat/chat.gateway.ts
- 이미지와 같이 메시지를 보내지 않고 메시지 단독으로 전송 시 전송되지 않던 문제 해결
- 본인이 채팅을 치고 채팅방을 나갔다 오면 읽음으로 처리되는 문제 해결
- 채팅방 삭제 기능 구현 중
> fix : 전송 기능 문제 해결 및 읽음처리 해결

- next/app/hooks/useObjectControls.js
- next/app/sim/collaboration/[id]/page.tsx
- next/components/sim/collaboration/CollaborationIndicators.jsx
- next/components/sim/collaboration/useCollaboration.js
- next/components/sim/mainsim/DraggableModel.jsx
- next/components/sim/mainsim/useObjectControls.js
- next/components/sim/useStore.js
- socket/package-lock.json
- socket/package.json
- socket/src/app.module.ts
- socket/src/collab/collab.gateway.ts
- socket/src/redis/redis.service.ts
- 상대방이 선택한 모델은 클릭해도 선택이 안 됩니다.
- 상대방이 선택 중인 모델은 위에 말풍선이 뜹니다.
- 모델 선택 후 일정 시간 경과 시 락이 해제됩니다.
- 일정시간 이상 비활동시 퇴장처리됩니다. 퇴장된 사용자가 선택 중이였던 모델은 락이 풀립니다.
> feat 일단 동시가구편집 완료

- next/components/sim/AutoSaveIndicator.tsx
- 자동저장 팝업 → 협업모드 종료 버튼과  안겹치도록 중앙으로 위치 이동
> fix : 자동저장 팝업 위치 수정

- next/components/chat/components/ChatListView.tsx
- next/components/chat/hooks/useUserSearch.ts
- next/lib/api/likes.ts
- next/next.config.ts
```
images: {
remotePatterns: [
{
protocol: "https",
hostname: "**",
},
{
protocol: "http",
hostname: "**",
},
{
protocol: "https",
hostname: "wheretoput-bucket.s3.ap-northeast-2.amazonaws.com",
pathname: "**",
},
],
},
```
처음에 이미지 안 불러와지고, 새로고침해야 불러와지는 문제 해결할 수 있다ㅗㄱ 해서 바꿔봄.
> fix: 이미지 불러오기 설정 및 localhost:3000 추가 제거

- next/app/api/sim/furnitures/click/route.ts
- next/lib/api/achievement/checkUserOwnRoom.ts
> fix: 업적 버그 수정

- next/app/sim/[id]/page.tsx
- next/app/sim/collaboration/[id]/page.tsx
- next/components/chat/hooks/useChatConnection.ts
- next/components/chat/hooks/useChatRooms.ts
- next/components/rooms/CommentsList.tsx
- next/components/rooms/RoomPageClient.tsx
- next/components/sim/SimulatorCore.tsx
- next/components/sim/achievement/components/ArchievementToast.tsx
- next/components/sim/collaboration/useCollaboration.js
- next/components/sim/useStore.js
- next/lib/api/fetchFurnitures.ts
> chore : console.log() 제거

- next/app/api/backend/rooms/route.ts
- next/components/chat/hooks/useChatMessages.ts
- next/lib/api/achievement/checkAchievement.ts
> fix: 마지막 메시지 중복되는거 처리 

- next/app/api/rooms/route.ts
- next/app/api/sim/load/[room_id]/route.ts
- next/app/api/sim/save/route.ts
- next/app/sim/mobile/[id]/page.tsx
- next/components/sim/SimulatorCore.tsx
- next/components/sim/collaboration/useCollaboration.js
- next/components/sim/mainsim/ControlIcons.jsx
- next/components/sim/mobile/MobileHeader.tsx
- next/components/sim/useStore.js
- next/lib/client/socket.ts
- next/prisma/schema.prisma
- socket/src/collab/collab.gateway.ts
- 공유 버튼 새로 추가. 이걸로 가능
- url은 `wheretoput.store`로
- 이걸 위해 4개의 columns추가
- `room.rooms`에 `wall_color`, `floor_color`, `background_color`, `environment_preset`
> feat: 모바일QR 공유, 벽/바닥/배경색, 조명환경 저장/동시편집 가능

- next/components/CreateRoomModal.jsx
- next/components/FloorPlanEditor.jsx
- next/components/chat/components/shared/MessageBubble.tsx
- next/package.json
- [v] 부분지우기/지우기 모드 사이드바 수정
- [v] 집생성하기 → alert -> 모달창으로 수정
- [v] 채팅방 안에서 프로필 사진  클릭시 마이페이지 이동
> fix:  주요 기능 개선

- next/components/sim/mainsim/KeyboardControls.jsx
현재 wasd조작이 안 씹히는 대신 wasd를 처음 누를 때 팍 튀는 문제가 있어서
클로드에게 속도처리 방식을 개선해 달라고 요청했습니다.
> fix: WASD 한번에 팍 튀는 현상 해결

- next/app/api/sim/save/route.ts
- next/app/crawling.py
- next/components/rooms/FurnituresList.tsx
- next/components/sim/SimulatorCore.tsx
- next/components/sim/history/HistoryControls.tsx
- next/components/sim/mainsim/CollapsibleSidebar.jsx
- next/components/sim/mainsim/RotationControl.jsx
- next/components/sim/mainsim/SelectedModelSidebar.jsx
- next/components/sim/mainsim/useDeleteKey.js
- next/components/sim/side/ShoppingLink.tsx
- next/components/sim/side/item/ItemSection.tsx
- 데코레이션 , 욕실용품 등
- ShoppingLink 컴포넌트 재사용
> feat : 09.09 (화) 작업내역

- docker-compose.yml
- next/components/main/HomeCardList.tsx
- 주목받는집 → 마우스 호버시 검은색 스크린 안뜨도록 수정
> chore: 주목받는집 호버링 개선

- next/app/api/achievement/sse/route.ts
- next/app/api/sim/furnitures/click/route.ts
- next/app/sim/[id]/page.tsx
- next/app/sim/collaboration/[id]/page.tsx
- next/app/sim/mobile/[id]/page.tsx
- next/components/sim/SimSideView.tsx
- next/components/sim/SimulatorCore.tsx
- next/components/sim/achievement/ArchievementToast.tsx
- next/components/sim/mainsim/ControlPanel.jsx
- next/components/sim/side/SideTitle.tsx
- next/components/sim/side/item/ItemSection.tsx
- next/components/sim/useStore.js
- next/lib/api/achievement/utils/sse.ts
> fix: 협업 모드에서 나가가 눌렀을 때 바로 상세 페이지로 나가지게 하기

- next/app/api/chat/sse/notify/route.ts
- next/app/api/chat/sse/route.ts
- next/components/chat/ChatButton.tsx
- next/components/chat/hooks/useChatMessages.ts
- next/components/chat/hooks/useChatRooms.ts
- next/components/chat/hooks/useChatSSE.ts
- next/components/chat/types/chat-types.ts
- socket/src/chat/chat.gateway.ts
> feat : SSE 로 구현

- next/components/sim/CanvasCapture.tsx
- next/components/sim/SimulatorCore.tsx
- next/components/sim/mainsim/CaptureControlPanel.jsx
- next/components/sim/mainsim/CaptureHandler.jsx
- next/components/sim/mainsim/CaptureModal.jsx
- next/components/sim/mainsim/ControlPanel.jsx
- next/components/sim/slices/uiSlice.js
- next/lib/api/saveRoom.ts
- Capture 버튼을 누르면 아래와 같은 팝업창에서 다운로드 및 썸네일 설정이 가능합니다.
- 타인의 방은 다운로드만 가능하고 썸네일 설정은 불가능합니다.
- 더 이상 저장 시 자동으로 썸네일이 변경되지 않습니다.
> fix: 스냅샷 개선

- next/app/follows/page.tsx
- next/cache-medata.json
- next/components/rooms/FurnituresList.tsx
- next/components/rooms/RoomPageClient.tsx
- next/components/sim/side/ShoppingLink.tsx
- next/components/users/components/Follow.tsx
- next/components/users/components/UserTabs.tsx
-  상대방의 프로필에서 팔로워 / 팔로잉  삭제버튼 안뜨도록 수정 
-  UI 수정
> fix : UI 수정 

- next/app/api/backend/rooms/direct/route.ts
- next/app/api/rooms/clone/route.ts
- next/components/chat/ChatButton.tsx
- next/components/chat/components/ChatListView.tsx
- next/components/chat/components/ChatPopup.tsx
- next/components/chat/hooks/useChatRooms.ts
- next/components/sim/SimulatorCore.tsx
- next/components/sim/slices/environmentSlice.js
- next/components/sim/slices/roomSlice.js
- next/components/sim/wall/wallUtils.js
- next/lib/services/simulator/extractRoomInfo.ts
- next/lib/textureUtils.js
- next/prisma/schema.prisma
- socket/prisma/schema.prisma
Reverts KJ-9th-NMM-Team2/wheretoput#377
> Revert "Revert "9월17일 00시 52분 배포""

- next/components/sim/SimulatorCore.tsx
- next/components/sim/slices/roomSlice.js
- next/components/sim/wall/wallUtils.js
Reverts KJ-9th-NMM-Team2/wheretoput#378
> Revert "Revert "fix: 카메라가 방의 가운데에 오게 설정""

- next/components/chat/components/ChatListView.tsx
- next/components/chat/components/ChatRoomView.tsx
- next/components/chat/components/CollaborationChatRoomSelector.tsx
- next/components/chat/components/GameStyleChatPopup.tsx
- next/components/sim/side/WallTools.tsx
- 벽 도구 버튼 위로 변경
- 협업모드 채팅창 위치변경
- 협업모드 채팅창 드래그 온오프 가능하게 변경
- 협업모드 채팅창 오프시에 클릭시 시뮬레이션이 눌러지게 변경
- 기본 채팅창 UI 전체적으로 파랑색으로 변경
> fix : 협업모드 채팅창, 채팅창 위치 및 UI 변경

- next/lib/wallDetection.js
기존에는 평행하기만 하고 실제 거리는 떨어져 있는 선들이 같은 선으로 인식되어 검출되는 문제가 있었습니다.
예를 들어 --[         벽       ] -------------------[        벽        ]-----
인 경우 두 벽이 합쳐지는 문제가 있었습니다.
```js
// 두 선이 평행한지 확인
areParallelLines(line1, line2, maxDistance, angleThreshold) {
// 각도 비교
const angle1 =
(Math.atan2(line1.y2 - line1.y1, line1.x2 - line1.x1) * 180) / Math.PI;
const angle2 =
(Math.atan2(line2.y2 - line2.y1, line2.x2 - line2.x1) * 180) / Math.PI;
let angleDiff = Math.abs(angle1 - angle2);
if (angleDiff > 90) angleDiff = 180 - angleDiff;
if (angleDiff > angleThreshold) return false;
// 평행선 간의 거리 계산
const distance = this.distanceBetweenParallelLines(line1, line2);
if (distance > maxDistance) return false;
// 겹침 구간 검증 추가
// 수직선인지 수평선인지 판단
const isVertical = Math.abs(angle1) > 45 && Math.abs(angle1) < 135;
let …
```
> fix: 평행선 검출 시 좌표가 겹치지 않는 경우 검출하지 않음

- next/app/error.tsx
- next/app/error/page.tsx
- next/app/global-error.tsx
- next/app/not-found.tsx
- next/lib/auth.ts
> fix: 에러페이지 도입

- next/app/api/rooms/clone/route.ts
- next/components/FloorPlanEditor.jsx
- next/components/rooms/RoomPageClient.tsx
- next/components/sim/SimulatorCore.tsx
- next/components/sim/mainsim/hooks/useObjectControls.js
- next/components/sim/slices/environmentSlice.js
- next/components/sim/slices/roomSlice.js
- next/prisma/schema.prisma
- socket/prisma/schema.prisma
- 비공개 방 복제 시 복제 표시하지 않음
- 모델 로딩 실패해도 뻗지 않게 처리 (errorBoundary 사용)
- 기본 배경 회색으로 변경
- 방 a -> b로 넘어가 로딩할 시, 기존 방 a이 보이지 않게 처리
- 벽 자석 감지 16ms 쓰로틀링으로, 무한 상태 업데이트 방지
> Bugfixes 좀 많음

- next/components/sim/mainsim/DraggableModel.jsx
- next/components/sim/mainsim/hooks/useObjectControls.js
- 바운딩 박스 안 물건도 클릭하면 (e.g., 침대 위 베개) 잘 선택되게 처리했습니다. 다만, three.js 한계상 호버링 박스는 뜨지 않습니다.
- 호버할 때 여러 물건을 연달아 이동하는 경우 호버링이 먹히지 않는 ㅁ누제를 개선했습ㄴ디ㅏ.
> fix: 바운딩박스 안 물건도 위치 이동 가능

- next/components/sim/SimulatorCore.tsx
전체 화면 등에서 dpr이 상승해 랙이 걸리는 문제를 해결(?)
> hotfix: dpr을 1로 고정
